In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import files
uploaded = files.upload()

Saving ml_dataset3.csv to ml_dataset3.csv

In [3]:
import pandas as pd

# Replace 'your_file.csv' with the uploaded file name
Drone_data = pd.read_csv('ml_dataset3.csv')
Drone_data

# Display first 5 rows
Drone_data.head(5)

,Name,Type,Control Range,Battery Type,Weight,Price,Actual Price,Discount (%)
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,40,Lithium Battery,200,2297.0,4999.0,54.0
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,300,AA Battery,500,10255.0,11000.0,6.0
2,Clubmall E88 Pro 4K Camera Drone with WiFi FPV...,Professional Drone,102,AA Rechargeable Battery,150,1994.0,5999.0,66.0
3,Orivox A17 Aerial Drone with 4K Dual Camera - ...,Mini Drone,50,Lithium Battery,150,2455.0,4999.0,50.0
4,Orivox M3 Max Mini Drone with Pro Features HD ...,Mini Drone,200,Lithium Battery,200,4998.0,5999.0,16.0

In [ ]:
Drone_data.shape

(821, 8)

In [ ]:
print("number of rows = ", Drone_data.shape[0])

number of rows =  821

In [ ]:
print("number of columns = ", Drone_data.shape[1])

number of columns =  8

In [ ]:
Drone_data.columns

Index(['Name', 'Type', 'Control Range', 'Battery Type', 'Weight', 'Price',
       'Actual Price', 'Discount (%)'],
      dtype='object')

In [ ]:
Drone_data.dtypes

Name              object
Type              object
Control Range      int64
Battery Type      object
Weight             int64
Price            float64
Actual Price     float64
Discount (%)     float64
dtype: object

In [ ]:
Drone_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 821 entries, 0 to 820
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           821 non-null    object
 1   Type           821 non-null    object
 2   Control Range  821 non-null    int64
 3   Battery Type   821 non-null    object
 4   Weight         821 non-null    int64
 5   Price          813 non-null    float64
 6   Actual Price   813 non-null    float64
 7   Discount (%)   810 non-null    float64
dtypes: float64(3), int64(2), object(3)
memory usage: 51.4+ KB

In [ ]:
Drone_data.columns

Index(['Name', 'Type', 'Control Range', 'Battery Type', 'Weight', 'Price',
       'Actual Price', 'Discount (%)'],
      dtype='object')

In [ ]:
Drone_tab1 = Drone_data[['Name', 'Type','Price','Discount (%)']]
Drone_tab1.head(6)

,Name,Type,Price,Discount (%)
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,2297.0,54.0
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,10255.0,6.0
2,Clubmall E88 Pro 4K Camera Drone with WiFi FPV...,Professional Drone,1994.0,66.0
3,Orivox A17 Aerial Drone with 4K Dual Camera - ...,Mini Drone,2455.0,50.0
4,Orivox M3 Max Mini Drone with Pro Features HD ...,Mini Drone,4998.0,16.0
5,ERH India A17 Aerial Drone with 4K Dual Camera...,Mini Drone,4376.0,27.0

In [ ]:
Drone_data.columns

Index(['Name', 'Type', 'Control Range', 'Battery Type', 'Weight', 'Price',
       'Actual Price', 'Discount (%)'],
      dtype='object')

In [ ]:
Drone_tab2 = Drone_data[['Name', 'Type', 'Control Range', 'Battery Type', 'Weight', 'Price',
       'Actual Price']]
Drone_tab2.head(2)

,Name,Type,Control Range,Battery Type,Weight,Price,Actual Price
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,40,Lithium Battery,200,2297.0,4999.0
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,300,AA Battery,500,10255.0,11000.0

In [ ]:
Drone_tab2.to_csv('Modified-Drone-dataset.csv')

In [ ]:
Drone_tab3 = Drone_data.drop(columns=[ 'Control Range', 'Battery Type'], axis=1)
Drone_tab3

,Name,Type,Weight,Price,Actual Price,Discount (%)
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,200,2297.0,4999.0,54.0
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,500,10255.0,11000.0,6.0
2,Clubmall E88 Pro 4K Camera Drone with WiFi FPV...,Professional Drone,150,1994.0,5999.0,66.0
3,Orivox A17 Aerial Drone with 4K Dual Camera - ...,Mini Drone,150,2455.0,4999.0,50.0
4,Orivox M3 Max Mini Drone with Pro Features HD ...,Mini Drone,200,4998.0,5999.0,16.0
...,...,...,...,...,...,...
816,Swa Mi Drone WiFi Camera Remote Control-Motion...,Professional Drone,250,2244.0,8999.0,75.0
817,Radhikadro e449 Drone,Professional Drone,350,2447.0,4999.0,51.0
818,Mevara fOlDaBlE-ToY-DrOnE pHoToGrApHy GeStUrE-...,Professional Drone,400,1799.0,6999.0,74.0
819,mayuri E8 WiFi Camera Remote Control 360 Flip ...,Professional Drone,250,2799.0,5999.0,53.0
820,Swa Mi E88 Drone Best Adults/Kids Drone With W...,Professional Drone,300,2705.0,8999.0,69.0

In [ ]:
Drone_tab3['Model'] = 'Drone Model'
Drone_tab3

,Name,Type,Weight,Price,Actual Price,Discount (%),Model
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,200,2297.0,4999.0,54.0,Drone Model
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,500,10255.0,11000.0,6.0,Drone Model
2,Clubmall E88 Pro 4K Camera Drone with WiFi FPV...,Professional Drone,150,1994.0,5999.0,66.0,Drone Model
3,Orivox A17 Aerial Drone with 4K Dual Camera - ...,Mini Drone,150,2455.0,4999.0,50.0,Drone Model
4,Orivox M3 Max Mini Drone with Pro Features HD ...,Mini Drone,200,4998.0,5999.0,16.0,Drone Model
...,...,...,...,...,...,...,...
816,Swa Mi Drone WiFi Camera Remote Control-Motion...,Professional Drone,250,2244.0,8999.0,75.0,Drone Model
817,Radhikadro e449 Drone,Professional Drone,350,2447.0,4999.0,51.0,Drone Model
818,Mevara fOlDaBlE-ToY-DrOnE pHoToGrApHy GeStUrE-...,Professional Drone,400,1799.0,6999.0,74.0,Drone Model
819,mayuri E8 WiFi Camera Remote Control 360 Flip ...,Professional Drone,250,2799.0,5999.0,53.0,Drone Model
820,Swa Mi E88 Drone Best Adults/Kids Drone With W...,Professional Drone,300,2705.0,8999.0,69.0,Drone Model

In [ ]:
Drone_data.columns

Index(['Name', 'Type', 'Control Range', 'Battery Type', 'Weight', 'Price',
       'Actual Price', 'Discount (%)'],
      dtype='object')

In [ ]:
col_dict = {
    'Name': 'Drone_Name',
    'Type': 'Drone_Type',
    'Control Range': 'Control_Range',
    'Battery Type': 'Battery_Type',
    'Weight': 'Weight_g',
    'Price': 'Selling_Price',
    'Actual Price': 'Original_Price',
    'Discount (%)': 'Discount_Percent'
}

In [ ]:
Drone_data = Drone_data.rename(columns = col_dict)
Drone_data.head(5)

,Drone_Name,Drone_Type,Control_Range,Battery_Type,Weight_g,Selling_Price,Original_Price,Discount_Percent
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,40,Lithium Battery,200,2297.0,4999.0,54.0
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,300,AA Battery,500,10255.0,11000.0,6.0
2,Clubmall E88 Pro 4K Camera Drone with WiFi FPV...,Professional Drone,102,AA Rechargeable Battery,150,1994.0,5999.0,66.0
3,Orivox A17 Aerial Drone with 4K Dual Camera - ...,Mini Drone,50,Lithium Battery,150,2455.0,4999.0,50.0
4,Orivox M3 Max Mini Drone with Pro Features HD ...,Mini Drone,200,Lithium Battery,200,4998.0,5999.0,16.0

In [ ]:
Drone_data.select_dtypes(include = 'object').head()

,Drone_Name,Drone_Type,Battery_Type
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,Lithium Battery
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,AA Battery
2,Clubmall E88 Pro 4K Camera Drone with WiFi FPV...,Professional Drone,AA Rechargeable Battery
3,Orivox A17 Aerial Drone with 4K Dual Camera - ...,Mini Drone,Lithium Battery
4,Orivox M3 Max Mini Drone with Pro Features HD ...,Mini Drone,Lithium Battery

In [ ]:
Drone_data.select_dtypes(exclude = 'object').head()

   Control_Range  Weight_g  Selling_Price  Original_Price  Discount_Percent
0             40       200         2297.0          4999.0              54.0
1            300       500        10255.0         11000.0               6.0
2            102       150         1994.0          5999.0              66.0
3             50       150         2455.0          4999.0              50.0
4            200       200         4998.0          5999.0              16.0

In [ ]:
Categorical_col = Drone_data.select_dtypes(include = 'object').columns
Categorical_col

Index(['Drone_Name', 'Drone_Type', 'Battery_Type'], dtype='object')

In [5]:
Numerical_col = Drone_data.select_dtypes(exclude = 'object').columns
Numerical_col

Index(['Control Range', 'Weight', 'Price', 'Actual Price', 'Discount (%)'], dtype='object')

In [6]:
cat_df = Drone_data.select_dtypes(include = 'object')
cat_df

,Name,Type,Battery Type
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,Lithium Battery
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,AA Battery
2,Clubmall E88 Pro 4K Camera Drone with WiFi FPV...,Professional Drone,AA Rechargeable Battery
3,Orivox A17 Aerial Drone with 4K Dual Camera - ...,Mini Drone,Lithium Battery
4,Orivox M3 Max Mini Drone with Pro Features HD ...,Mini Drone,Lithium Battery
...,...,...,...
816,Swa Mi Drone WiFi Camera Remote Control-Motion...,Professional Drone,Lithium Battery
817,Radhikadro e449 Drone,Professional Drone,Lithium Battery
818,Mevara fOlDaBlE-ToY-DrOnE pHoToGrApHy GeStUrE-...,Professional Drone,Lithium Battery
819,mayuri E8 WiFi Camera Remote Control 360 Flip ...,Professional Drone,Lithium Battery
820,Swa Mi E88 Drone Best Adults/Kids Drone With W...,Professional Drone,Lithium Battery

In [7]:
Categorical_col = list(Drone_data.select_dtypes(include = 'object').columns)
Categorical_col

['Name', 'Type', 'Battery Type']

In [8]:
Numerical_col = list(Drone_data.select_dtypes(exclude = 'object').columns)
Numerical_col

['Control Range', 'Weight', 'Price', 'Actual Price', 'Discount (%)']

In [9]:
Drone_data.duplicated().any()

np.True_

In [10]:
Drone_data.duplicated().sum()

np.int64(3)

In [11]:
Drone_data.head(10)

,Name,Type,Control Range,Battery Type,Weight,Price,Actual Price,Discount (%)
0,"Zyamalox ZX drone with camera 4k ,12 MP ,fly 3...",Mini Drone,40,Lithium Battery,200,2297.0,4999.0,54.0
1,Fitpro M3 Ultra Beginner Drone 2.4G Mini FPV H...,Mini Drone,300,AA Battery,500,10255.0,11000.0,6.0
2,Clubmall E88 Pro 4K Camera Drone with WiFi FPV...,Professional Drone,102,AA Rechargeable Battery,150,1994.0,5999.0,66.0
3,Orivox A17 Aerial Drone with 4K Dual Camera - ...,Mini Drone,50,Lithium Battery,150,2455.0,4999.0,50.0
4,Orivox M3 Max Mini Drone with Pro Features HD ...,Mini Drone,200,Lithium Battery,200,4998.0,5999.0,16.0
5,ERH India A17 Aerial Drone with 4K Dual Camera...,Mini Drone,100,Lithium Battery,200,4376.0,5999.0,27.0
6,Kidsbuddy New Good Quality Quadcopter E88 WIFI...,Mini Drone,15,AA Rechargeable Battery,350,2299.0,12999.0,82.0
7,tmwilla Foldable-RC-Quadcopter-Altitude-Hold-H...,Professional Drone,117,AA Battery,300,1884.0,4999.0,62.0
8,CLYSOL New Good Quality Quadcopter E88 WIFI Dr...,Mini Drone,100,Lithium Battery,400,2326.0,12999.0,82.0
9,Clubics RC Brushless Motor J18 Drone 4k hd Cam...,Professional Drone,100,Lithium Battery,400,12600.0,13999.0,9.0

In [12]:
Drone_data2 = Drone_data.drop_duplicates()

In [13]:
Drone_data2.shape

(818, 8)

In [14]:
Drone_data2.duplicated().any()

np.False_

In [15]:
#Indexing columns
df = Drone_data2.isnull().sum().reset_index()
#Rename column
df.columns = ['column', 'null_records']
#Create new colums and find out null value percentage
df['% null records'] = (df['null_records']/818)*100
df

          column  null_records  % null records
0           Name             0        0.000000
1           Type             0        0.000000
2  Control Range             0        0.000000
3   Battery Type             0        0.000000
4         Weight             0        0.000000
5          Price             8        0.977995
6   Actual Price             8        0.977995
7   Discount (%)            11        1.344743

In [ ]:
Numerical_col = list(Drone_data.select_dtypes(exclude = 'object').columns)
Numerical_col

['Control_Range',
 'Weight_g',
 'Selling_Price',
 'Original_Price',
 'Discount_Percent']

In [ ]:
sell_mean = Drone_data2['Selling_Price'].mean()
sell_mean

np.float64(2983.3802469135803)

In [ ]:
Drone_data2['Selling_Price'] = Drone_data2['Selling_Price'].fillna(sell_mean)

/tmp/ipykernel_8612/1563447485.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Drone_data2['Selling_Price'] = Drone_data2['Selling_Price'].fillna(sell_mean)

In [ ]:
Drone_data2.isnull().sum()

Drone_Name           0
Drone_Type           0
Control_Range        0
Battery_Type         0
Weight_g             0
Selling_Price        0
Original_Price       8
Discount_Percent    11
dtype: int64

In [ ]:
Org_mean = Drone_data2['Original_Price'].mean()
Org_mean

np.float64(8718.677777777777)

In [ ]:
Drone_data2['Original_Price'] = Drone_data2['Original_Price'].fillna(Org_mean)

/tmp/ipykernel_8612/1997113637.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Drone_data2['Original_Price'] = Drone_data2['Original_Price'].fillna(Org_mean)

In [ ]:
Drone_data2.isnull().sum()

Drone_Name           0
Drone_Type           0
Control_Range        0
Battery_Type         0
Weight_g             0
Selling_Price        0
Original_Price       0
Discount_Percent    11
dtype: int64

In [ ]:
Dis_mean = Drone_data2['Discount_Percent'].mean()
Dis_mean

np.float64(63.87112763320942)

In [ ]:
Drone_data2['Discount_Percent'] = Drone_data2['Discount_Percent'].fillna(Dis_mean)

/tmp/ipykernel_8612/1820459991.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Drone_data2['Discount_Percent'] = Drone_data2['Discount_Percent'].fillna(Dis_mean)

In [ ]:
Drone_data2.isnull().sum()

Drone_Name          0
Drone_Type          0
Control_Range       0
Battery_Type        0
Weight_g            0
Selling_Price       0
Original_Price      0
Discount_Percent    0
dtype: int64