In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import files
uploaded = files.upload()

Saving ml dataset 2.csv to ml dataset 2.csv

In [3]:
import pandas as pd

# Replace 'your_file.csv' with the uploaded file name
animal_data = pd.read_csv('ml dataset 2.csv')
animal_data

# Display first 5 rows
animal_data.head(5)

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually)
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12

In [4]:
# Last 5 rows of data
animal_data.tail(5)

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
200,Yak,140-160,500-1200,"Brown, Black",20-25,Herbivore,Mountains,"Snow Leopards, Wolves",24,"Himalayas, Central Asia",Least Concern,Bovidae,215-280,24,Group-based,10-50
201,Yellow-Eyed Penguin,60-65,1-3,"Yellow, White",Up to 20,Carnivore,Coastal Areas,"Seals, Orcas",25,New Zealand,Endangered,Spheniscidae,80-90,25,Solitary,1
202,Yeti Crab,Up to 15,Up to 0.5,"White, Hairy",Up to 20,Omnivore,Hydrothermal Vents,Not Applicable,Not Applicable,Pacific Ocean,Not Evaluated,Kiwaidae,Not Applicable,Not Applicable,Solitary,Not Applicable
203,Zebra,220-340,400-900,"Black, White",20-25,Herbivore,Grasslands,"Lions, Hyenas",25,Africa,Least Concern,Equidae,180-365,25,Group-based,5-20
204,Zebra Shark,Up to 330,Up to 32,"Brown, Yellowish",25-30,Carnivore,Coral Reefs,Larger Fish,20,Indo-Pacific region,Endangered,Stegostomatidae,10-25,20,Solitary,Up to 25

In [5]:
# Number of rows and column in dataset: Size of the dat

animal_data.shape # (rows [0th indexing position], columns[1st indexing position])

(205, 16)

In [6]:
print("number of rows = ", animal_data.shape[0])

number of rows =  205

In [7]:
print("number of rows = ", animal_data.shape[1])

number of rows =  16

In [8]:
### List of Columns/ Features
animal_data.columns

Index(['Animal', 'Height (cm)', 'Weight (kg)', 'Color', 'Lifespan (years)',
       'Diet', 'Habitat', 'Predators', 'Average Speed (km/h)',
       'Countries Found', 'Conservation Status', 'Family',
       'Gestation Period (days)', 'Top Speed (km/h)', 'Social Structure',
       'Offspring per Birth'],
      dtype='object')

In [9]:
### Data types of columns
animal_data.dtypes

Animal                     object
Height (cm)                object
Weight (kg)                object
Color                      object
Lifespan (years)           object
Diet                       object
Habitat                    object
Predators                  object
Average Speed (km/h)       object
Countries Found            object
Conservation Status        object
Family                     object
Gestation Period (days)    object
Top Speed (km/h)           object
Social Structure           object
Offspring per Birth        object
dtype: object

In [10]:
animal_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Animal                   205 non-null    object
 1   Height (cm)              205 non-null    object
 2   Weight (kg)              205 non-null    object
 3   Color                    205 non-null    object
 4   Lifespan (years)         205 non-null    object
 5   Diet                     205 non-null    object
 6   Habitat                  205 non-null    object
 7   Predators                205 non-null    object
 8   Average Speed (km/h)     205 non-null    object
 9   Countries Found          205 non-null    object
 10  Conservation Status      205 non-null    object
 11  Family                   205 non-null    object
 12  Gestation Period (days)  205 non-null    object
 13  Top Speed (km/h)         205 non-null    object
 14  Social Structure         205 non-null    object
 15  Offspring per Birth      205 non-null    object
dtypes: object(16)
memory usage: 25.8+ KB

In [11]:
animal_tab1 = animal_data[['Animal','Color','Lifespan (years)','Countries Found']]
animal_tab1.head(6)

,Animal,Color,Lifespan (years),Countries Found
0,Aardvark,Grey,20-30,Africa
1,Aardwolf,Yellow-brown,10-12,Eastern and Southern Africa
2,African Elephant,Grey,60-70,Africa
3,African Lion,Tan,10-14,Africa
4,African Wild Dog,Multicolored,10-12,Sub-Saharan Africa
5,Alpine Ibex,Brown,15-20,European Alps

In [12]:
animal_data.columns

Index(['Animal', 'Height (cm)', 'Weight (kg)', 'Color', 'Lifespan (years)',
       'Diet', 'Habitat', 'Predators', 'Average Speed (km/h)',
       'Countries Found', 'Conservation Status', 'Family',
       'Gestation Period (days)', 'Top Speed (km/h)', 'Social Structure',
       'Offspring per Birth'],
      dtype='object')

In [13]:
animal_tab2 = animal_data[['Animal','Color','Weight (kg)','Lifespan (years)','Countries Found','Average Speed (km/h)']]
animal_tab2.head(2)

,Animal,Color,Weight (kg),Lifespan (years),Countries Found,Average Speed (km/h)
0,Aardvark,Grey,40-65,20-30,Africa,40
1,Aardwolf,Yellow-brown,8-14,10-12,Eastern and Southern Africa,24-30

In [14]:

animal_tab2.to_csv('Modified-Car-dataset.csv')

In [15]:
animal_tab3 = animal_data.drop(columns=['Conservation Status','Social Structure'], axis=1)
animal_tab3

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Family,Gestation Period (days),Top Speed (km/h),Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Orycteropodidae,210-240,40,1
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Hyaenidae,90,40,2-5
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Elephantidae,640-660,40,1
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Felidae,98-105,80,2-4 (usually)
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Canidae,70,56,10-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,Yak,140-160,500-1200,"Brown, Black",20-25,Herbivore,Mountains,"Snow Leopards, Wolves",24,"Himalayas, Central Asia",Bovidae,215-280,24,10-50
201,Yellow-Eyed Penguin,60-65,1-3,"Yellow, White",Up to 20,Carnivore,Coastal Areas,"Seals, Orcas",25,New Zealand,Spheniscidae,80-90,25,1
202,Yeti Crab,Up to 15,Up to 0.5,"White, Hairy",Up to 20,Omnivore,Hydrothermal Vents,Not Applicable,Not Applicable,Pacific Ocean,Kiwaidae,Not Applicable,Not Applicable,Not Applicable
203,Zebra,220-340,400-900,"Black, White",20-25,Herbivore,Grasslands,"Lions, Hyenas",25,Africa,Equidae,180-365,25,5-20
204,Zebra Shark,Up to 330,Up to 32,"Brown, Yellowish",25-30,Carnivore,Coral Reefs,Larger Fish,20,Indo-Pacific region,Stegostomatidae,10-25,20,Up to 25

In [16]:
#add colum  dataset field rows with name cae dataset
animal_tab3['Species'] = 'Animal Species'
animal_tab3

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Family,Gestation Period (days),Top Speed (km/h),Offspring per Birth,Species
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Orycteropodidae,210-240,40,1,Animal Species
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Hyaenidae,90,40,2-5,Animal Species
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Elephantidae,640-660,40,1,Animal Species
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Felidae,98-105,80,2-4 (usually),Animal Species
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Canidae,70,56,10-12,Animal Species
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,Yak,140-160,500-1200,"Brown, Black",20-25,Herbivore,Mountains,"Snow Leopards, Wolves",24,"Himalayas, Central Asia",Bovidae,215-280,24,10-50,Animal Species
201,Yellow-Eyed Penguin,60-65,1-3,"Yellow, White",Up to 20,Carnivore,Coastal Areas,"Seals, Orcas",25,New Zealand,Spheniscidae,80-90,25,1,Animal Species
202,Yeti Crab,Up to 15,Up to 0.5,"White, Hairy",Up to 20,Omnivore,Hydrothermal Vents,Not Applicable,Not Applicable,Pacific Ocean,Kiwaidae,Not Applicable,Not Applicable,Not Applicable,Animal Species
203,Zebra,220-340,400-900,"Black, White",20-25,Herbivore,Grasslands,"Lions, Hyenas",25,Africa,Equidae,180-365,25,5-20,Animal Species
204,Zebra Shark,Up to 330,Up to 32,"Brown, Yellowish",25-30,Carnivore,Coral Reefs,Larger Fish,20,Indo-Pacific region,Stegostomatidae,10-25,20,Up to 25,Animal Species

In [17]:

animal_data.columns

Index(['Animal', 'Height (cm)', 'Weight (kg)', 'Color', 'Lifespan (years)',
       'Diet', 'Habitat', 'Predators', 'Average Speed (km/h)',
       'Countries Found', 'Conservation Status', 'Family',
       'Gestation Period (days)', 'Top Speed (km/h)', 'Social Structure',
       'Offspring per Birth'],
      dtype='object')

In [18]:
col_dict = {
    'Animal': 'Animal_Name',
    'Height (cm)': 'Height_cm',
    'Weight (kg)': 'Weight_kg',
    'Lifespan (years)': 'Lifespan_yrs',
    'Diet': 'Diet_Type',
    'Habitat': 'Habitat',
    'Predators': 'Predators_Type',
    'Average Speed (km/h)': 'Avg_Speed_kmh'
}

In [19]:
animal_data = animal_data.rename(columns = col_dict)
animal_data.head(5)

,Animal_Name,Height_cm,Weight_kg,Color,Lifespan_yrs,Diet_Type,Habitat,Predators_Type,Avg_Speed_kmh,Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually)
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12

In [20]:
# Categorical Columns
animal_data.select_dtypes(include = 'object').head()

,Animal_Name,Height_cm,Weight_kg,Color,Lifespan_yrs,Diet_Type,Habitat,Predators_Type,Avg_Speed_kmh,Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually)
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12

In [21]:
# Numerical Columns
animal_data.select_dtypes(exclude = 'object').head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [22]:
Categorical_col = animal_data.select_dtypes(include = 'object').columns
Categorical_col

Index(['Animal_Name', 'Height_cm', 'Weight_kg', 'Color', 'Lifespan_yrs',
       'Diet_Type', 'Habitat', 'Predators_Type', 'Avg_Speed_kmh',
       'Countries Found', 'Conservation Status', 'Family',
       'Gestation Period (days)', 'Top Speed (km/h)', 'Social Structure',
       'Offspring per Birth'],
      dtype='object')

In [23]:
Numerical_col = animal_data.select_dtypes(exclude = 'object').columns
Numerical_col

Index([], dtype='object')

In [24]:
animal_df = animal_data.select_dtypes(include = 'object')
animal_df

,Animal_Name,Height_cm,Weight_kg,Color,Lifespan_yrs,Diet_Type,Habitat,Predators_Type,Avg_Speed_kmh,Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually)
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,Yak,140-160,500-1200,"Brown, Black",20-25,Herbivore,Mountains,"Snow Leopards, Wolves",24,"Himalayas, Central Asia",Least Concern,Bovidae,215-280,24,Group-based,10-50
201,Yellow-Eyed Penguin,60-65,1-3,"Yellow, White",Up to 20,Carnivore,Coastal Areas,"Seals, Orcas",25,New Zealand,Endangered,Spheniscidae,80-90,25,Solitary,1
202,Yeti Crab,Up to 15,Up to 0.5,"White, Hairy",Up to 20,Omnivore,Hydrothermal Vents,Not Applicable,Not Applicable,Pacific Ocean,Not Evaluated,Kiwaidae,Not Applicable,Not Applicable,Solitary,Not Applicable
203,Zebra,220-340,400-900,"Black, White",20-25,Herbivore,Grasslands,"Lions, Hyenas",25,Africa,Least Concern,Equidae,180-365,25,Group-based,5-20
204,Zebra Shark,Up to 330,Up to 32,"Brown, Yellowish",25-30,Carnivore,Coral Reefs,Larger Fish,20,Indo-Pacific region,Endangered,Stegostomatidae,10-25,20,Solitary,Up to 25

In [25]:
Categorical_col = list(animal_data.select_dtypes(include = 'object').columns)
Categorical_col

['Animal_Name',
 'Height_cm',
 'Weight_kg',
 'Color',
 'Lifespan_yrs',
 'Diet_Type',
 'Habitat',
 'Predators_Type',
 'Avg_Speed_kmh',
 'Countries Found',
 'Conservation Status',
 'Family',
 'Gestation Period (days)',
 'Top Speed (km/h)',
 'Social Structure',
 'Offspring per Birth']

In [26]:
Numerical_col = list(animal_data.select_dtypes(exclude = 'object').columns)
Numerical_col

[]

In [27]:
# Checking for duplicate records
animal_data.duplicated().any()

np.False_

In [28]:
# Number of duplicate records i.e., duplicate rows
animal_data.duplicated().sum()

np.int64(0)

In [29]:
animal_data.head(10)

,Animal_Name,Height_cm,Weight_kg,Color,Lifespan_yrs,Diet_Type,Habitat,Predators_Type,Avg_Speed_kmh,Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually)
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12
5,Alpine Ibex,67-101,19-120,Brown,15-20,Herbivore,"Mountains, Alpine","Wolves, Golden Eagles",56-64,European Alps,Least Concern,Bovidae,150,56-64,Group-based,1
6,Amazon Rainforest Frog,2-13,Up to 0.5,Various,4-17,Insectivore,Amazon Rainforest,"Birds, Snakes",0.1-1,Amazon Rainforest,Not Evaluated,Dendrobatidae,10-15,0.8,Solitary,Up to 40
7,American Bison,152-186,"318-1,000",Brown,15-20,Herbivore,"Grasslands, Plains","Wolves, Grizzly Bears",40-56,North America,Near Threatened,Bovidae,270-290,56,Group-based,1
8,Anteater,52-91,22-41,"Brown, White",15-20,Insectivore,"Grasslands, Forests","Jaguars, Pumas",24,Central and South America,Least Concern,Myrmecophagidae,190-210,24,Solitary,1
9,Arabian Horse,140-160,380-1000,Various,25-30,Herbivore,"Middle East, North Africa","Humans, Predators",65,"Middle East, North Africa",Not Applicable,Equidae,330-342,65,Herd-based,1

In [30]:
animal_data.shape

(205, 16)

In [31]:
#Indexing columns
df = animal_data.isnull().sum().reset_index()
#Rename column
df.columns = ['column', 'null_records']
#Create new colums and Find out null value percentage
df['% null records'] = (df['null_records']/205)*100
df

                     column  null_records  % null records
0               Animal_Name             0             0.0
1                 Height_cm             0             0.0
2                 Weight_kg             0             0.0
3                     Color             0             0.0
4              Lifespan_yrs             0             0.0
5                 Diet_Type             0             0.0
6                   Habitat             0             0.0
7            Predators_Type             0             0.0
8             Avg_Speed_kmh             0             0.0
9           Countries Found             0             0.0
10      Conservation Status             0             0.0
11                   Family             0             0.0
12  Gestation Period (days)             0             0.0
13         Top Speed (km/h)             0             0.0
14         Social Structure             0             0.0
15      Offspring per Birth             0             0.0

In [32]:
animal_data.head(1)

,Animal_Name,Height_cm,Weight_kg,Color,Lifespan_yrs,Diet_Type,Habitat,Predators_Type,Avg_Speed_kmh,Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1

In [33]:
animal_data.columns

Index(['Animal_Name', 'Height_cm', 'Weight_kg', 'Color', 'Lifespan_yrs',
       'Diet_Type', 'Habitat', 'Predators_Type', 'Avg_Speed_kmh',
       'Countries Found', 'Conservation Status', 'Family',
       'Gestation Period (days)', 'Top Speed (km/h)', 'Social Structure',
       'Offspring per Birth'],
      dtype='object')

In [34]:
num_cols = ['Height_cm', 'Weight_kg', 'Lifespan_yrs', 'Avg_Speed_kmh',
            'Gestation Period (days)', 'Top Speed (km/h)', 'Offspring per Birth']

for col in num_cols:
    animal_data[col] = pd.to_numeric(animal_data[col], errors='coerce')

In [35]:
Numerical_col = list(animal_data.select_dtypes(exclude = 'object').columns)
Numerical_col

['Height_cm',
 'Weight_kg',
 'Lifespan_yrs',
 'Avg_Speed_kmh',
 'Gestation Period (days)',
 'Top Speed (km/h)',
 'Offspring per Birth']

In [36]:
Categorical_col = list(animal_data.select_dtypes(include = 'object').columns)
Categorical_col

['Animal_Name',
 'Color',
 'Diet_Type',
 'Habitat',
 'Predators_Type',
 'Countries Found',
 'Conservation Status',
 'Family',
 'Social Structure']