**Import libraies**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Upload the data**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving ml dataset 1.csv to ml dataset 1.csv

**import the data**

In [ ]:
import pandas as pd

# Replace 'your_file.csv' with the uploaded file name
car_data = pd.read_csv('ml dataset 1.csv')
car_data

# Display first 5 rows
car_data.head(5)

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [ ]:
# Last 5 rows of data
car_data.tail(5)

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [ ]:
# Number of rows and column in dataset: Size of the dat

car_data.shape # (rows [0th indexing position], columns[1st indexing position])

(11914, 16)

In [ ]:
print("number of rows = ", car_data.shape[0])

number of rows =  11914

In [ ]:
print("number of columns = ", car_data.shape[1])

number of columns =  16

In [ ]:
### List of Columns/ Features
car_data.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [ ]:
### Data types of columns
car_data.dtypes

Make                  object
Model                 object
Year                   int64
Engine Fuel Type      object
Engine HP            float64
Engine Cylinders     float64
Transmission Type     object
Driven_Wheels         object
Number of Doors      float64
Market Category       object
Vehicle Size          object
Vehicle Style         object
highway MPG            int64
city mpg               int64
Popularity             int64
MSRP                   int64
dtype: object

In [ ]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               11914 non-null  object
 1   Model              11914 non-null  object
 2   Year               11914 non-null  int64
 3   Engine Fuel Type   11911 non-null  object
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object
 7   Driven_Wheels      11914 non-null  object
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object
 10  Vehicle Size       11914 non-null  object
 11  Vehicle Style      11914 non-null  object
 12  highway MPG        11914 non-null  int64
 13  city mpg           11914 non-null  int64
 14  Popularity         11914 non-null  int64
 15  MSRP               11914 non-null  int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.5+ MB

In [ ]:
car_tab1 = car_data[['Make', 'Model', 'Year', 'MSRP']]
car_tab1.head(6)

  Make       Model  Year   MSRP
0  BMW  1 Series M  2011  46135
1  BMW    1 Series  2011  40650
2  BMW    1 Series  2011  36350
3  BMW    1 Series  2011  29450
4  BMW    1 Series  2011  34500
5  BMW    1 Series  2012  31200

In [ ]:

car_data.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [ ]:
)car_tab2 = car_data[['Make', 'Model', 'Year','highway MPG', 'city mpg', 'Popularity', 'MSRP']]
car_tab2.head(2

  Make       Model  Year  highway MPG  city mpg  Popularity   MSRP
0  BMW  1 Series M  2011           26        19        3916  46135
1  BMW    1 Series  2011           28        19        3916  40650

In [ ]:
car_tab2.to_csv('Modified-Car-dataset.csv')

In [ ]:
car_tab3 = car_data.drop(columns=['Market Category', 'Popularity'], axis=1)
car_tab3

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Vehicle Size,Vehicle Style,highway MPG,city mpg,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Coupe,26,19,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Convertible,28,19,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Coupe,28,20,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Coupe,28,18,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Convertible,28,18,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,Midsize,4dr Hatchback,23,16,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,Midsize,4dr Hatchback,23,16,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,Midsize,4dr Hatchback,23,16,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,Midsize,4dr Hatchback,23,16,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Midsize,Sedan,26,17,28995

In [ ]:
#add colum  dataset field rows with name cae dataset
car_tab3['Dataset'] = 'Car Dataset'
car_tab3

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Vehicle Size,Vehicle Style,highway MPG,city mpg,MSRP,Dataset
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Coupe,26,19,46135,Car Dataset
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Convertible,28,19,40650,Car Dataset
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Coupe,28,20,36350,Car Dataset
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Coupe,28,18,29450,Car Dataset
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Convertible,28,18,34500,Car Dataset
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,Midsize,4dr Hatchback,23,16,46120,Car Dataset
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,Midsize,4dr Hatchback,23,16,56670,Car Dataset
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,Midsize,4dr Hatchback,23,16,50620,Car Dataset
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,Midsize,4dr Hatchback,23,16,50920,Car Dataset
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Midsize,Sedan,26,17,28995,Car Dataset

In [ ]:
car_data.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [ ]:
col_dict = {'Engine Fuel Type' : "Fuel_Type",
            'Engine HP' : 'Engine_HP',
            'Engine Cylinders' : 'No_of_Cylinders',
            'Transmission Type' : 'Transmission_Type',
            'Number of Doors' : 'No_of_Doors',
            'Market Category' : 'Market_Category',
            'Vehicle Size' : 'Vehicle_Size',
            'Vehicle Style' : 'Vehicle_Style',
            'highway MPG' : 'Highway_MPG',
            'city mpg' : 'City_MPG',
            'MSRP' : 'Car_Price'}

In [ ]:
car_data = car_data.rename(columns = col_dict)
car_data.head(5)

,Make,Model,Year,Fuel_Type,Engine_HP,No_of_Cylinders,Transmission_Type,Driven_Wheels,No_of_Doors,Market_Category,Vehicle_Size,Vehicle_Style,Highway_MPG,City_MPG,Popularity,Car_Price
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [ ]:
# Categorical Columns
car_data.select_dtypes(include = 'object').head()

,Make,Model,Fuel_Type,Transmission_Type,Driven_Wheels,Market_Category,Vehicle_Size,Vehicle_Style
0,BMW,1 Series M,premium unleaded (required),MANUAL,rear wheel drive,"Factory Tuner,Luxury,High-Performance",Compact,Coupe
1,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,"Luxury,Performance",Compact,Convertible
2,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,"Luxury,High-Performance",Compact,Coupe
3,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,"Luxury,Performance",Compact,Coupe
4,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,Luxury,Compact,Convertible

In [ ]:
# Numerical Columns
car_data.select_dtypes(exclude = 'object').head()

,Year,Engine_HP,No_of_Cylinders,No_of_Doors,Highway_MPG,City_MPG,Popularity,Car_Price
0,2011,335.0,6.0,2.0,26,19,3916,46135
1,2011,300.0,6.0,2.0,28,19,3916,40650
2,2011,300.0,6.0,2.0,28,20,3916,36350
3,2011,230.0,6.0,2.0,28,18,3916,29450
4,2011,230.0,6.0,2.0,28,18,3916,34500

In [ ]:
Categorical_col = car_data.select_dtypes(include = 'object').columns
Categorical_col

Index(['Make', 'Model', 'Fuel_Type', 'Transmission_Type', 'Driven_Wheels',
       'Market_Category', 'Vehicle_Size', 'Vehicle_Style'],
      dtype='object')

In [ ]:
Numerical_col = car_data.select_dtypes(exclude = 'object').columns
Numerical_col

Index(['Year', 'Engine_HP', 'No_of_Cylinders', 'No_of_Doors', 'Highway_MPG',
       'City_MPG', 'Popularity', 'Car_Price'],
      dtype='object')

In [ ]:
cat_df = car_data.select_dtypes(include = 'object')
cat_df

,Make,Model,Fuel_Type,Transmission_Type,Driven_Wheels,Market_Category,Vehicle_Size,Vehicle_Style
0,BMW,1 Series M,premium unleaded (required),MANUAL,rear wheel drive,"Factory Tuner,Luxury,High-Performance",Compact,Coupe
1,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,"Luxury,Performance",Compact,Convertible
2,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,"Luxury,High-Performance",Compact,Coupe
3,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,"Luxury,Performance",Compact,Coupe
4,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,Luxury,Compact,Convertible
...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,premium unleaded (required),AUTOMATIC,all wheel drive,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback
11910,Acura,ZDX,premium unleaded (required),AUTOMATIC,all wheel drive,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback
11911,Acura,ZDX,premium unleaded (required),AUTOMATIC,all wheel drive,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback
11912,Acura,ZDX,premium unleaded (recommended),AUTOMATIC,all wheel drive,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback
11913,Lincoln,Zephyr,regular unleaded,AUTOMATIC,front wheel drive,Luxury,Midsize,Sedan

In [ ]:
Categorical_col = list(car_data.select_dtypes(include = 'object').columns)
Categorical_col

['Make',
 'Model',
 'Fuel_Type',
 'Transmission_Type',
 'Driven_Wheels',
 'Market_Category',
 'Vehicle_Size',
 'Vehicle_Style']

In [ ]:
Numerical_col = list(car_data.select_dtypes(exclude = 'object').columns)
Numerical_col

['Year',
 'Engine_HP',
 'No_of_Cylinders',
 'No_of_Doors',
 'Highway_MPG',
 'City_MPG',
 'Popularity',
 'Car_Price']

In [ ]:
# Checking for duplicate records
car_data.duplicated().any()

np.True_

In [ ]:
# Number of duplicate records i.e., duplicate rows
car_data.duplicated().sum()

np.int64(715)

In [ ]:
car_data.head(10)

,Make,Model,Year,Fuel_Type,Engine_HP,No_of_Cylinders,Transmission_Type,Driven_Wheels,No_of_Doors,Market_Category,Vehicle_Size,Vehicle_Style,Highway_MPG,City_MPG,Popularity,Car_Price
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
5,BMW,1 Series,2012,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,31200
6,BMW,1 Series,2012,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,26,17,3916,44100
7,BMW,1 Series,2012,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,39300
8,BMW,1 Series,2012,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,36900
9,BMW,1 Series,2013,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,27,18,3916,37200

In [ ]:
# Remove/Delete Duplicate Records
car_data2 = car_data.drop_duplicates()  # is a clean datasets now

In [ ]:
car_data2.shape

(11199, 16)

In [ ]:
car_data2.duplicated().any()

np.False_

In [ ]:
#Indexing columns
df = car_data2.isnull().sum().reset_index()
#Rename column
df.columns = ['column', 'null_records']
#Create new colums and find out null value percentage
df['% null records'] = (df['null_records']/11199)*100
df

               column  null_records  % null records
0                Make             0        0.000000
1               Model             0        0.000000
2                Year             0        0.000000
3           Fuel_Type             3        0.026788
4           Engine_HP            69        0.616126
5     No_of_Cylinders            30        0.267881
6   Transmission_Type             0        0.000000
7       Driven_Wheels             0        0.000000
8         No_of_Doors             6        0.053576
9     Market_Category          3376       30.145549
10       Vehicle_Size             0        0.000000
11      Vehicle_Style             0        0.000000
12        Highway_MPG             0        0.000000
13           City_MPG             0        0.000000
14         Popularity             0        0.000000
15          Car_Price             0        0.000000

In [ ]:
car_data2['Fuel_Type']

0           premium unleaded (required)
1           premium unleaded (required)
2           premium unleaded (required)
3           premium unleaded (required)
4           premium unleaded (required)
                      ...
11909       premium unleaded (required)
11910       premium unleaded (required)
11911       premium unleaded (required)
11912    premium unleaded (recommended)
11913                  regular unleaded
Name: Fuel_Type, Length: 11199, dtype: object

In [ ]:
mode_fueltype = car_data2['Fuel_Type'].mode()[0]
mode_fueltype

'regular unleaded'

In [ ]:
## Frequency of categorical column
car_data2['Fuel_Type'].value_counts()

Fuel_Type
regular unleaded                                6658
premium unleaded (required)                     1956
premium unleaded (recommended)                  1392
flex-fuel (unleaded/E85)                         887
diesel                                           150
electric                                          66
flex-fuel (premium unleaded required/E85)         53
flex-fuel (premium unleaded recommended/E85)      26
flex-fuel (unleaded/natural gas)                   6
natural gas                                        2
Name: count, dtype: int64

In [ ]:
car_data2['Fuel_Type'] = car_data2['Fuel_Type'].fillna(mode_fueltype)

/tmp/ipykernel_3109/917741824.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car_data2['Fuel_Type'] = car_data2['Fuel_Type'].fillna(mode_fueltype)

In [ ]:
car_data2.isnull().sum()

Make                    0
Model                   0
Year                    0
Fuel_Type               0
Engine_HP              69
No_of_Cylinders        30
Transmission_Type       0
Driven_Wheels           0
No_of_Doors             6
Market_Category      3376
Vehicle_Size            0
Vehicle_Style           0
Highway_MPG             0
City_MPG                0
Popularity              0
Car_Price               0
dtype: int64

In [ ]:
hp_mean = car_data2['Engine_HP'].mean()
hp_mean

np.float64(253.38885893980233)

In [ ]:
car_data2['Engine_HP'] = car_data2['Engine_HP'].fillna(hp_mean)

/tmp/ipykernel_3109/1856510687.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car_data2['Engine_HP'] = car_data2['Engine_HP'].fillna(hp_mean)

In [ ]:
car_data2.isnull().sum()

Make                    0
Model                   0
Year                    0
Fuel_Type               0
Engine_HP               0
No_of_Cylinders        30
Transmission_Type       0
Driven_Wheels           0
No_of_Doors             6
Market_Category      3376
Vehicle_Size            0
Vehicle_Style           0
Highway_MPG             0
City_MPG                0
Popularity              0
Car_Price               0
dtype: int64