In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [7]:
#Import pandas
import pandas as pd

print("pandas version:", pd.__version__)

pandas version: 2.3.3

In [8]:
Data = [10,20,30,40,50]
print(Data)

[10, 20, 30, 40, 50]

In [9]:
Data = [10,20,30,40,50] # now ist all integer but when you print mix datatypes then you can not used mathematical operators
series = pd.Series(Data) #it convert list into arrays by module Series 
print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [10]:
# A series is a one dimentional array with lable (index)
Data = [10,20,30,40,50]
series = pd.Series(Data, index=['A', 'B', 'C', 'D', 'F'])
print("Series example:")
print(series)

Series example:
A    10
B    20
C    30
D    40
F    50
dtype: int64

In [11]:
#creating a dataframe using dictionary
# it convert unstructure data into structure formatt
data_dict = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 45],
    'Salary': [50000, 60000, 75000, 80000, 90000]
}

df = pd.DataFrame(data_dict)

print("DataFrame Example:")
print(df)

DataFrame Example:
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   75000
3    David   40   80000
4      Eva   45   90000

In [12]:
# Display top and bottom rows
print(df.head(3))  # First 3 rows
print(df.tail(2))  # Last 2 rows

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   75000
    Name  Age  Salary
3  David   40   80000
4    Eva   45   90000

In [13]:
# Basic info
print(df.info())   # Provides a concise summary of the DataFrame (index dtype, column dtypes, non-null values, and memory usage)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Salary  5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes
None

In [14]:
# Summary statistics
print(df.describe())  # Generates descriptive statistics for numeric columns (mean, std, min, quartiles, max)

             Age        Salary
count   5.000000      5.000000
mean   35.000000  71000.000000
std     7.905694  15968.719423
min    25.000000  50000.000000
25%    30.000000  60000.000000
50%    35.000000  75000.000000
75%    40.000000  80000.000000
max    45.000000  90000.000000

In [15]:
# Column names
print(df.columns)    # Returns the Index of column labels

Index(['Name', 'Age', 'Salary'], dtype='object')

In [16]:
# Shape of dataset (rows, columns)
print(df.shape)      # Returns a tuple representing the dimensionality of the DataFrame

(5, 3)

In [17]:
# Selecting one column
print(df['Name'])  # This returns a Series containing all values from the 'Name' column.

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: Name, dtype: object

In [18]:
# Selecting multiple columns
print(df[['Name', 'Salary']])  # Double brackets create a DataFrame with the specified columns.

      Name  Salary
0    Alice   50000
1      Bob   60000
2  Charlie   75000
3    David   80000
4      Eva   90000

In [19]:
# Selecting by index position (using iloc)
print(df.iloc[0])    # Returns the first row as a Series (integer-location based indexing).

Name      Alice
Age          25
Salary    50000
Name: 0, dtype: object

In [20]:
print(df.iloc[1:3])  # Returns rows 1 and 2 (slice is exclusive of the end index).

      Name  Age  Salary
1      Bob   30   60000
2  Charlie   35   75000

In [21]:
# Selecting by label (using loc)
print(df.loc[0:2, ['Name', 'Salary']])  # Selects rows 0 to 2 and the specified columns by label.

      Name  Salary
0    Alice   50000
1      Bob   60000
2  Charlie   75000

In [22]:
#iloc vs loc:iloc: Integer-based indexing (position-based)Uses integer positions (0, 1, 2, ...)
#Exclusive of the end index in slices (like Python lists)
#Example: df.iloc[0:2] gets rows 0 and 1
#loc: Label-based indexing (name-based)Uses row/column 
#labelsInclusive of the end index in slices (unlike Python lists
#)Example: df.loc[0:2] gets rows with labels 0, 1, and 2

In [32]:
# Add a new column
df['Tax'] = df['Salary'] * 0.10
print(df)

      Name  Age  Salary   Bonus      Tax
0    Alice   25   60000  2750.0   6000.0
1      Bob   30   70000  3250.0   7000.0
2  Charlie   35   85000  4000.0   8500.0
3    David   40   90000  4250.0   9000.0
4      Eva   45  100000  4750.0  10000.0

In [33]:
# Update existing column
df['Salary'] = df['Salary'] + 5000
print(df)

      Name  Age  Salary   Bonus      Tax
0    Alice   25   65000  2750.0   6000.0
1      Bob   30   75000  3250.0   7000.0
2  Charlie   35   90000  4000.0   8500.0
3    David   40   95000  4250.0   9000.0
4      Eva   45  105000  4750.0  10000.0

In [34]:
# Delete a column
df.drop('Tax', axis=1, inplace=True)
print(df)

      Name  Age  Salary   Bonus
0    Alice   25   65000  2750.0
1      Bob   30   75000  3250.0
2  Charlie   35   90000  4000.0
3    David   40   95000  4250.0
4      Eva   45  105000  4750.0

In [28]:
# Arithmetic operations
df['Bonus'] = df['Salary'] * 0.05
print(df)

      Name  Age  Salary   Bonus
0    Alice   25   55000  2750.0
1      Bob   30   65000  3250.0
2  Charlie   35   80000  4000.0
3    David   40   85000  4250.0
4      Eva   45   95000  4750.0

In [40]:
# Introduce missing values
df.loc[2, "Age"] = None
print("With Missing Data:\n", df)

With Missing Data:
       Name   Age  Salary   Bonus
0    Alice  25.0   65000  2750.0
1      Bob  30.0   75000  3250.0
2  Charlie   NaN   90000  4000.0
3    David  40.0   95000  4250.0
4      Eva  45.0  105000  4750.0

In [42]:
# Check for null values
print(df.isnull())

    Name    Age  Salary  Bonus
0  False  False   False  False
1  False  False   False  False
2  False   True   False  False
3  False  False   False  False
4  False  False   False  False

In [69]:
# Fill missing values
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

      Name   Age  Salary   Bonus  Salary_Rank Joining_Date  Joining_Year
0    Alice  25.0   65000  2750.0          5.0   2020-12-31          2020
1      Bob  30.0   75000  3250.0          4.0   2021-12-31          2021
2  Charlie  35.0   90000  4000.0          3.0   2022-12-31          2022
3    David  40.0   95000  4250.0          2.0   2023-12-31          2023
4      Eva  45.0  105000  4750.0          1.0   2024-12-31          2024

In [44]:
# Drop rows with missing data
# df.dropna(inplace=True)
# print("After Handling Missing Data:\n", df)

In [45]:
# Filter data where Age > 30
print(df[df['Age'] > 30])

      Name   Age  Salary   Bonus
2  Charlie  35.0   90000  4000.0
3    David  40.0   95000  4250.0
4      Eva  45.0  105000  4750.0

In [46]:
# Multiple conditions
print(df[(df['Age'] > 30) & (df['Salary'] > 60000)])

      Name   Age  Salary   Bonus
2  Charlie  35.0   90000  4000.0
3    David  40.0   95000  4250.0
4      Eva  45.0  105000  4750.0

In [47]:
# Sort by Salary
print(df.sort_values(by='Salary', ascending=False))

      Name   Age  Salary   Bonus
4      Eva  45.0  105000  4750.0
3    David  40.0   95000  4250.0
2  Charlie  35.0   90000  4000.0
1      Bob  30.0   75000  3250.0
0    Alice  25.0   65000  2750.0

In [48]:
# Sort by multiple columns
print(df.sort_values(by=['Age', 'Salary'], ascending=[True, False]))

      Name   Age  Salary   Bonus
0    Alice  25.0   65000  2750.0
1      Bob  30.0   75000  3250.0
2  Charlie  35.0   90000  4000.0
3    David  40.0   95000  4250.0
4      Eva  45.0  105000  4750.0

In [49]:
# Rank the salaries
df['Salary_Rank'] = df['Salary'].rank(ascending=False)
print(df)

      Name   Age  Salary   Bonus  Salary_Rank
0    Alice  25.0   65000  2750.0          5.0
1      Bob  30.0   75000  3250.0          4.0
2  Charlie  35.0   90000  4000.0          3.0
3    David  40.0   95000  4250.0          2.0
4      Eva  45.0  105000  4750.0          1.0

In [53]:
#grouping and aggregation



# Group by variable
# Group by example
group_data = df.groupby('Age')['Salary'].mean()
print(group_data)

# Multiple aggregations
agg_data = df.groupby('Age').agg({'Salary': ['mean', 'max', 'min']})
print(agg_data)

Age
25.0     65000.0
30.0     75000.0
35.0     90000.0
40.0     95000.0
45.0    105000.0
Name: Salary, dtype: float64
        Salary
          mean     max     min
Age
25.0   65000.0   65000   65000
30.0   75000.0   75000   75000
35.0   90000.0   90000   90000
40.0   95000.0   95000   95000
45.0  105000.0  105000  105000

In [54]:
#merging and joining dataframe


# Merge on 'Name' column
dept_data = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# Merge on multiple columns
merged_df = pd.merge(df, dept_data, on='Name')
print(merged_df)

      Name   Age  Salary   Bonus  Salary_Rank Department
0    Alice  25.0   65000  2750.0          5.0         HR
1      Bob  30.0   75000  3250.0          4.0         IT
2  Charlie  35.0   90000  4000.0          3.0    Finance
3    David  40.0   95000  4250.0          2.0         IT
4      Eva  45.0  105000  4750.0          1.0         HR

In [55]:
#concatination

In [59]:
df1 = df.head(2)
df2 = df.tail(2)

combined = pd.concat([df1, df2])
print(combined)

    Name   Age  Salary   Bonus  Salary_Rank
0  Alice  25.0   65000  2750.0          5.0
1    Bob  30.0   75000  3250.0          4.0
3  David  40.0   95000  4250.0          2.0
4    Eva  45.0  105000  4750.0          1.0

In [57]:
# statistical and mathematical function

In [58]:
print("Mean Salary:", df['Salary'].mean())
print("Max Age:", df['Age'].max())
print("Min Age:", df['Age'].min())
print("Standard Deviation of Salary:", df['Salary'].std())

Mean Salary: 86000.0
Max Age: 45.0
Min Age: 25.0
Standard Deviation of Salary: 15968.719422671313

In [65]:
# Extract Year
df['Joining_Year'] = df['Joining_Date'].dt.year

print(df[['Name', 'Joining_Date', 'Joining_Year']])

print(df)

      Name Joining_Date  Joining_Year
0    Alice   2020-12-31          2020
1      Bob   2021-12-31          2021
2  Charlie   2022-12-31          2022
3    David   2023-12-31          2023
4      Eva   2024-12-31          2024
      Name   Age  Salary   Bonus  Salary_Rank Joining_Date  Joining_Year
0    Alice  25.0   65000  2750.0          5.0   2020-12-31          2020
1      Bob  30.0   75000  3250.0          4.0   2021-12-31          2021
2  Charlie  35.0   90000  4000.0          3.0   2022-12-31          2022
3    David  40.0   95000  4250.0          2.0   2023-12-31          2023
4      Eva  45.0  105000  4750.0          1.0   2024-12-31          2024

In [63]:
# Add a data column
df['Joining_Date'] = pd.date_range(start='2020-01-01', periods=len(df), freq='YE')
df

      Name   Age  Salary   Bonus  Salary_Rank Joining_Date  Joining_Year
0    Alice  25.0   65000  2750.0          5.0   2020-12-31          2020
1      Bob  30.0   75000  3250.0          4.0   2021-12-31          2021
2  Charlie  35.0   90000  4000.0          3.0   2022-12-31          2022
3    David  40.0   95000  4250.0          2.0   2023-12-31          2023
4      Eva  45.0  105000  4750.0          1.0   2024-12-31          2024

In [66]:
# Export final data

In [67]:
# save final data
df.to_csv('Pandas-final_output.csv', index=False)
print("Data saved successfully!")

Data saved successfully!